imageslideshow_index:
  path: /imageslideshow
  methods: [ GET ]
  defaults:
    _controller: PrestaShop\Module\ImageSlideshow\Controller\ImageSlideshowController::indexAction

imageslideshow_create:
  path: /imageslideshow/new
  methods: [GET, POST]
  defaults:
    _controller: PrestaShop\Module\ImageSlideshow\Controller\ImageSlideshowController::createAction
    _legacy_controller: ImageSlideshowController

imageslideshow_edit:
  path: /imageslideshow/{idImageSlideshow}/edit
  methods: [GET, POST]
  defaults:
    _controller: PrestaShop\Module\ImageSlideshow\Controller\ImageSlideshowController::editAction
    _legacy_controller: ImageSlideshowController
  requirements:
    idImageSlideshow: \d+

imageslideshow_delete:
  path: /imageslideshow/{idImageSlideshow}/delete
  methods: DELETE
  defaults:
    _controller: PrestaShop\Module\ImageSlideshow\Controller\ImageSlideshowController::deleteAction
  requirements:
    idImageSlideshow: \d+

imageslideshow_toggle:
  path: /imageslideshow/{idImageSlideshow}/toggle-status
  methods: POST
  defaults:
    _controller: PrestaShop\Module\ImageSlideshow\Controller\ImageSlideshowController::toggleStatusAction
  requirements:
    idImageSlideshow: \d+

imageslideshow_tinymce_test:
  path: /imageslideshow/tinymce-test
  methods: [ GET ]
  defaults:
    _controller: PrestaShop\Module\ImageSlideshow\Controller\ImageSlideshowController::tinymceTestAction
    _legacy_controller: ImageSlideshowController

# imageslideshow_slides ------------------------------------------------------------------------------------------------
imageslideshow_slides:
  path: /imageslideshow/{idImageSlideshow}/slides
  methods: [ GET, POST ]
  defaults:
    _controller: PrestaShop\Module\ImageSlideshow\Controller\ImageSlideshowSlideController::slidesAction
    _legacy_controller: ImageSlideshowController
    requirements:
      idImageSlideshow: \d+

imageslideshow_slides_add:
  path: /imageslideshow/{idImageSlideshow}/slides/add
  methods: [ GET, POST ]
  defaults:
    _controller: PrestaShop\Module\ImageSlideshow\Controller\ImageSlideshowSlideController::addAction
    _legacy_controller: ImageSlideshowController
  requirements:
    idImageSlideshow: \d+

imageslideshow_slides_edit:
  path: /imageslideshow/{idImageSlideshow}/slides/{idImageSlideshowSlide}/edit
  methods: [ GET, POST ]
  defaults:
    _controller: PrestaShop\Module\ImageSlideshow\Controller\ImageSlideshowSlideController::editAction
    _legacy_controller: ImageSlideshowController
  requirements:
    idImageSlideshow: \d+
    idImageSlideshowSlide: \d+

imageslideshow_slides_delete:
  path: /imageslideshow/{idImageSlideshow}/slides/{idImageSlideshowSlide}/delete
  methods: DELETE
  defaults:
    _controller: PrestaShop\Module\ImageSlideshow\Controller\ImageSlideshowSlideController::deleteAction
  requirements:
    idImageSlideshow: \d+
    idImageSlideshowSlide: \d+

imageslideshow_slides_toggle:
  path: /imageslideshow/{idImageSlideshow}/slides/{idImageSlideshowSlide}/toggle-status
  methods: POST
  defaults:
    _controller: PrestaShop\Module\ImageSlideshow\Controller\ImageSlideshowSlideController::toggleStatusAction
  requirements:
    idImageSlideshow: \d+
    idImageSlideshowSlide: \d+

imageslideshow_slides_add_update_positions:
  path: /imageslideshow/{idImageSlideshow}/slides/update-positions
  methods: POST
  defaults:
    _controller: PrestaShop\Module\ImageSlideshow\Controller\ImageSlideshowSlideController::updatePositionsAction
  requirements:
    idImageSlideshow: \d+

# imageslideshow_image -------------------------------------------------------------------------------------------------

imageslideshow_image_upload_temp:
  path: /imageslideshow/image/upload-temp
  methods: [ POST ]
  defaults:
    _controller: PrestaShop\Module\ImageSlideshow\Controller\ImageController::uploadTempAction

imageslideshow_image_fetch:
  path: /imageslideshow/image/fetch/{location}/{fileName}
  methods: [ GET ]
  defaults:
    _controller: PrestaShop\Module\ImageSlideshow\Controller\ImageController::fetchAction
  requirements:
    fileName: .+
