imageslideshow_index:
  path: /imageslideshow
  methods: [ GET ]
  defaults:
    _controller: PrestaShop\Module\ImageSlideshow\Controller\ImageSlideshowController::indexAction
    _legacy_controller: ImageSlideshowController
    _legacy_link: ImageSlideshow

imageslideshow_create:
  path: /imageslideshow/new
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\ImageSlideshow\Controller\ImageSlideshowController::createAction'
    _legacy_controller: ImageSlideshow
    _legacy_link: ImageSlideshow:create

imageslideshow_edit:
  path: /imageslideshow/{idImageSlideshow}/edit
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\ImageSlideshow\Controller\ImageSlideshowController::editAction'
    _legacy_controller: ImageSlideshow
    _legacy_link: ImageSlideshow:edit
    _legacy_parameters:
      id_image_slideshow: idImageSlideshow
  requirements:
    idImageSlideshow: \d+

imageslideshow_delete:
  path: /imageslideshow/{idImageSlideshow}/delete
  methods: DELETE
  defaults:
    _controller: 'PrestaShop\Module\ImageSlideshow\Controller\ImageSlideshowController::deleteAction'
    _legacy_controller: ImageSlideshow
    _legacy_link: ImageSlideshow:delete
    _legacy_parameters:
      id_image_slideshow: idImageSlideshow
  requirements:
    idImageSlideshow: \d+

imageslideshow_toggle:
  path: /imageslideshow/{idImageSlideshow}/toggle-status
  methods: POST
  defaults:
    _controller: 'PrestaShop\Module\ImageSlideshow\Controller\ImageSlideshowController::toggleStatusAction'
    _legacy_controller: ImageSlideshow
    _legacy_link: ImageSlideshow:toggleStatus
    _legacy_parameters:
      id_image_slideshow: idImageSlideshow
  requirements:
    idImageSlideshow: \d+

imageslideshow_slides:
  path: /imageslideshow/{idImageSlideshow}/slides
  methods: [ GET, POST ]
  defaults:
    _controller: 'PrestaShop\Module\ImageSlideshow\Controller\ImageSlideshowSlideController::slidesAction'
    _legacy_controller: ImageSlideshowSlide
    _legacy_link: ImageSlideshowSlide:products
    _legacy_parameters:
      id_image_slideshow: idImageSlideshow
    requirements:
      idImageSlideshow: \d+
