imports:
  - { resource: ./common.yml }

services:

  PrestaShop\Module\ImageSlideshow\Controller\ImageController:
    autoconfigure: true
    autowire: true

  PrestaShop\Module\ImageSlideshow\Controller\ImageSlideshowController:
    autoconfigure: true
    autowire: true

  PrestaShop\Module\ImageSlideshow\Controller\ImageSlideshowSlideController:
    autoconfigure: true
    autowire: true

  PrestaShop\Module\ImageSlideshow\Form\FileUploadType:
    arguments: [ '@router' ]
    tags: [ form.type ]

  PrestaShop\Module\ImageSlideshow\Form\ImageTempType:
    tags: [ form.type ]

  PrestaShop\Module\ImageSlideshow\Form\SlideEditorImageType:
    tags: [ form.type ]

  PrestaShop\Module\ImageSlideshow\Form\SlideshowType:
    arguments: [ '@translator' ]
    tags: [ form.type ]

  PrestaShop\Module\ImageSlideshow\Form\SlideType:
    arguments:
      - "@translator"
      - "@=service('prestashop.adapter.legacy.context').getLanguages()"
      - "@router"
    tags: [ form.type ]

  PrestaShop\Module\ImageSlideshow\Form\SlideshowFormDataHandler:
    arguments:
      - '@PrestaShop\Module\ImageSlideshow\Repository\ImageSlideshowRepository'
      - '@doctrine.orm.default_entity_manager'
      - '@property_accessor'

  PrestaShop\Module\ImageSlideshow\Form\SlideFormDataHandler:
    arguments:
      - '@PrestaShop\Module\ImageSlideshow\Repository\ImageSlideshowSlideRepository'
      - '@doctrine.orm.default_entity_manager'
      - '@PrestaShop\Module\ImageSlideshow\Service\ImageManager'

  PrestaShop\Module\ImageSlideshow\Grid\ImageSlideshowGridDefinitionFactory:
    arguments: [ '@translator' ]


  PrestaShop\Module\ImageSlideshow\Grid\ImageSlideshowQueryBuilder:
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
      - '@prestashop.core.query.doctrine_search_criteria_applicator'

  PrestaShop\Module\ImageSlideshow\Repository\ImageSlideshowSlideRepository:
    arguments: [ '@doctrine' ]
    tags: [ doctrine.repository_service ]

  PrestaShop\Module\ImageSlideshow\Service\ImageManager: ~

  prestashop.module.imageslideshow.form.builder.slideshow:
    class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder
    factory: [ '@prestashop.core.form.builder.form_builder_factory', 'create' ]
    arguments:
      - PrestaShop\Module\ImageSlideshow\Form\SlideshowType
      - '@PrestaShop\Module\ImageSlideshow\Repository\ImageSlideshowRepository'

  prestashop.module.imageslideshow.form.builder.slide:
    class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder
    factory: [ '@prestashop.core.form.builder.form_builder_factory', 'create' ]
    arguments:
      - PrestaShop\Module\ImageSlideshow\Form\SlideType
      - '@PrestaShop\Module\ImageSlideshow\Repository\ImageSlideshowSlideRepository'

  prestashop.module.imageslideshow.form.handler.slideshow:
    class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler
    factory: [ '@prestashop.core.form.identifiable_object.handler.form_handler_factory', 'create' ]
    arguments:
      - '@PrestaShop\Module\ImageSlideshow\Form\SlideshowFormDataHandler'

  prestashop.module.imageslideshow.form.handler.slide:
    class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler
    factory: [ '@prestashop.core.form.identifiable_object.handler.form_handler_factory', 'create' ]
    arguments:
      - '@PrestaShop\Module\ImageSlideshow\Form\SlideFormDataHandler'

  prestashop.module.imageslideshow.grid.data_provider.imageslideshow:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@PrestaShop\Module\ImageSlideshow\Grid\ImageSlideshowQueryBuilder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'imageslideshow'

  prestashop.module.imageslideshow.grid.grid_factory.imageslideshow:
    class: PrestaShop\PrestaShop\Core\Grid\GridFactory
    arguments:
      - '@PrestaShop\Module\ImageSlideshow\Grid\ImageSlideshowGridDefinitionFactory'
      - '@prestashop.module.imageslideshow.grid.data_provider.imageslideshow'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'
